### ISSUE TITLE
Change photo resolution

### ISSUE THREAD

**Issue by djszutu** [ingojaeckel/go-raspberry-pi-timelapse#2]
Hi Ingo! How do I change the photo resolution? 

I tried changing numbers in [go-raspberry-pi-timelapse/etc/os/timelapse.service](https://github.com/ingojaeckel/go-raspberry-pi-timelapse/blob/master/etc/os/timelapse.service) (changed 2186 and 1642 to 3264 and 2448 to change from 3.5 to 8 MP) and then re-running [go-raspberry-pi-timelapse/etc/os/3_install_timelapse_service.sh](https://github.com/ingojaeckel/go-raspberry-pi-timelapse/blob/master/etc/os/3_install_timelapse_service.sh), and then rebooted. But, the photos are still size 2186x1642, and I'm not sure what step I'm missing. 

Also, is there a way to change compression of the .jpg from 100% (no compression) to 75%? 

Thank you!
-Daphne

**Comment by ingojaeckel** [comment]
In general support to change the resolution via settings was committed in 48f664a102e8a258d2ce5df90fa3968466caa9dd. But it's not accessible via the web UI yet. Will work on that next.

**Comment by djszutu** [comment]
Thank you, Ingo!

**Comment by ingojaeckel** [comment]
Fixed in 741beeaa5730f81196e7fa2333b244dccfa1f0e2

**Comment by ingojaeckel** [comment]
I made another ticket to allow tweaking the compression ratio #3
